### ISSUE TITLE
[DPLM Workspace] Folders tree in not clear

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#942] opened 2016-02-12 16:21 UTC
![screen shot 2016-02-12 at 17 21 32](https://cloud.githubusercontent.com/assets/644898/13012806/130d86e8-d1ad-11e5-82b7-4b435d50b57f.png)

**Comment by mguimard** [comment] 2018-03-16 14:22
Duplicate of #1031

**Closed by mguimard** 2018-03-16 14:22 UTC
