### ISSUE TITLE
[DPLM] Impossible to unzip downloaded MacOsX archives...

### ISSUE THREAD

**Issue by ericdescargues** [docdoku/docdoku-plm#468] opened 2015-02-25 22:23 UTC

**Comment by mguimard** [comment] 2015-03-03 22:23
This should be good in next release, i'll tell you

**Comment by mguimard** [comment] 2015-03-09 15:48
Does it works now ?

**Comment by ericdescargues** [comment] 2015-03-24 22:18
Not yet...

**Comment by mguimard** [comment] 2015-03-26 07:44
Was caused by chrome not downloading correctly the zip. Closing the issue

**Closed by mguimard** 2015-03-26 07:44 UTC
