### ISSUE TITLE
ACL: Strange behavior of redirection when we disabe group or user  

### ISSUE THREAD

**Issue by chadidas** [docdoku/docdoku-plm#466] opened 2015-02-25 15:10 UTC
To reproduce the bug:

Create a milestone,  add an ACL that contains groups /users
disable your groups or/and users
Go back to the change management screen, you will be redirected to document management !! you cannot access to change management screen,
if we enable the disabled (groups/users)  then we can access to the change management screen,

**Comment by elisabelgenereux** [comment] 2015-03-02 09:46
Note: the redirection goes now to the workspaces page

**Comment by mguimard** [comment] 2015-06-19 13:49
Being in a group which is disabled restricts access to every module of the workspace. This is actually not a bug. Closing the issue.

**Closed by mguimard** 2015-06-19 13:49 UTC
Labels: bug
