### ISSUE TITLE
[Account creation] Account creation form doesn't appear on Google Chrome

### ISSUE THREAD

**Issue by ericdescargues** [docdoku/docdoku-plm#1093] opened 2017-04-12 08:34 UTC
When clicking on "Sign up" link on the home page, the account creation form doesn't appear on Google Chrome (Version 57.0.2987.133). It's OK on FF.

**Comment by mguimard** [comment] 2017-04-12 13:46
Seems that localStorage is not cleared in some cases (jwt is sent while it shoudn't be). Please clear offline data from chrome://settings/cookies and try again until we find the cause.

**Comment by ericdescargues** [comment] 2017-04-12 14:00
OK tested, it works after cleaning.

**Comment by mguimard** [comment] 2017-04-19 06:54
fixed by https://github.com/docdoku/docdoku-web-front/commit/53e855f52015cf2a35de7f8c312740546c9f8cae

**Closed by mguimard** 2017-04-19 06:54 UTC
Labels: bug
