### ISSUE TITLE
Doc Permalink

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#244] opened 2013-12-22 17:52 UTC
Many issues:
When opening the doc permalink a file downloading is immediately triggered.
PDF download button is missing.
iframe doesn't show pdf.
Moreover the header "Content-Disposition" should has a pdf extension otherwise when downloading the file its name is incorrect

**Comment by kelto** [comment] 2016-01-06 14:09
Closing this issue. The bug concerning the document permalink are fixed (and for the part permalink too). 
The rest of the issue is mainly for enhancement, and should be discussed in #892

**Closed by kelto** 2016-01-06 14:09 UTC
Labels: bug
