### ISSUE TITLE
[PDFConversion] Error while trying to view a pdf in web viewer

### ISSUE THREAD

**Issue by ericdescargues** [docdoku/docdoku-plm#1132] opened 2017-11-14 17:00 UTC
Error while trying to view a pdf file in web viewer on permanent link :

Caused by: java.lang.IllegalArgumentException: U+0410 ('Acyrillic') is not available in this font Helvetica-Bold (generic: NimbusSanL-Bold) encoding: WinAnsiEncoding
at org.apache.pdfbox.pdmodel.font.PDType1Font.encode(PDType1Font.java:401)
at org.apache.pdfbox.pdmodel.font.PDFont.encode(PDFont.java:316)
at org.apache.pdfbox.pdmodel.font.PDFont.getStringWidth(PDFont.java:345)
at rst.pdfbox.layout.text.StyledText.getWidth(StyledText.java:133)
at rst.pdfbox.layout.text.TextSequenceUtil.wordWrap(TextSequenceUtil.java:145)
at rst.pdfbox.layout.text.TextSequenceUtil.wordWrapToLines(TextSequenceUtil.java:251)
at rst.pdfbox.layout.text.TextSequenceUtil.getHeight(TextSequenceUtil.java:438)
at rst.pdfbox.layout.text.TextFlow.getHeight(TextFlow.java:254)
at rst.pdfbox.layout.elements.render.VerticalLayout.layoutAndDrawReleative(VerticalLayout.java:199)
at rst.pdfbox.layout.elements.render.VerticalLayout.renderReleative(VerticalLayout.java:148)
at rst.pdfbox.layout.elements.render.VerticalLayout.render(VerticalLayout.java:96)
at rst.pdfbox.layout.elements.render.VerticalLayout.render(VerticalLayout.java:79)
at rst.pdfbox.layout.elements.render.RenderContext.render(RenderContext.java:291)
at rst.pdfbox.layout.elements.Document.render(Document.java:259)
at rst.pdfbox.layout.elements.Document.save(Document.java:299)

**Comment by mguimard** [comment] 2018-02-05 15:34
Hey, thanks for this log.
The problem is that the character U+0410 isn't available in pdfbox font we use (old version from Helvetica). We will add support for general characters, and won't try to print  the glyphs that the font doesn't handle.

**Comment by mguimard** [comment] 2018-03-16 13:17
Fixed in dev branch, closing issue

**Closed by mguimard** 2018-03-16 13:17 UTC
Labels: bug
