### ISSUE TITLE
[health check] vault file permission

### ISSUE THREAD

**Issue by ludoBarel** [docdoku/docdoku-plm#1170] opened 2018-08-03 12:43 UTC
[health] request  return status code 500 when file doesn't have the right permissions to access.

logs generated by server : 

[2018-08-03T14:29:15.340+0200] [Payara 4.1] [GRAVE] [] [org.polarsys.eplmp.server.PlatformHealthManagerBean] [tid: _ThreadID=165 _ThreadName=http-thread-pool::http-listener-1(2)] [timeMillis: 1533299355340] [levelValue: 1000] [[
  Vaultpath is not writeable, please set appropriate rights on /var/lib/docdoku]]d

**Comment by mguimard** [comment] 2018-08-03 13:19
Actually not a bug, this is the expected behavior, closing issue.

**Closed by mguimard** 2018-08-03 13:19 UTC
Labels: bug
