### ISSUE TITLE
[Changes Management : Workflows] Unhandled system error

### ISSUE THREAD

**Issue by Jakovm00** [docdoku/docdoku-plm#979] opened 2016-04-18 07:13 UTC
When I create a new workflow, I receive the following error message:
Unhandled system error : org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.discoverUnregisteredNewObjects threw java.lang.IllegalStateException: During synchronization a new object was found through a relationship that was not marked cascade PERSIST: com.docdoku.core.workflow.Role@4c788776. in RepeatableWriteUnitOfWork.java at line 310

**Comment by mguimard** [comment] 2016-04-18 07:44
Hello, 

This is a duplicate of https://github.com/docdoku/docdoku-plm/issues/967
This bug has been discovered with chrome 49 update.

What you can do is : 
* Update your platform with latest `release-2.0` ear
* Use Firefox if you cannot update the platform

**Closed by mguimard** 2016-04-18 07:44 UTC

**Comment by Jakovm00** [comment] 2016-04-18 07:47
Thanks for the prompt reply Morgan.
Appreciated
