### ISSUE TITLE
[Assembly] Coordinates not saved

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#506] opened 2015-03-10 16:43 UTC
The part coordinates are not saved if the related "subParts-CADInstance" div is hidden.

**Comment by mguimard** [comment] 2015-03-12 15:48
Seems to happen only in casperjs, cannot reproduce it manually

**Comment by mguimard** [comment] 2015-03-13 12:34
Should not happen, as it fails when trying to change the value of an hidden element. This can't be done by human.  Closing the issue.

**Closed by mguimard** 2015-03-13 12:34 UTC
Labels: bug
