### ISSUE TITLE
Unable to view the home page

### ISSUE THREAD

**Issue by AmalSri** [docdoku/docdoku-plm#1142] opened 2018-03-13 05:19 UTC
I have deployed the version of docdoku-plm from the ear file available on the site on the payara server. But when I'm launching the application from the server it is showing a blank page. The url I used is 192.168.x.xx:8080/docdoku-server-rest, this was showing a blank page. I'm not getting the issue here. Can I get the correct URL which takes me to the main page of the PLM.

**Comment by mguimard** [comment] 2018-03-13 06:10
Duplicate of #1138

**Closed by mguimard** 2018-03-13 06:10 UTC
